[workspace]
authors = ["Maarten Paul <maarten.paul@gmail.com>"]
channels = ["conda-forge"]
name = "omero_transfer"
platforms = ["win-64", "linux-64"] #, "osx-64", "osx-arm64"
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11"
zeroc-ice = ">=3.6.5,<4"

[pypi-dependencies]
omero-py = ">=5.21.0, <6"
omero-cli-zarr = ">=0.6.1, <0.7"
omero-user-token = ">=0.4.1, <0.5"
omero-cli-transfer = { version = ">=1.3.0, <2.0", extras = ["rocrate"] }
